### ISSUE TITLE
Undefined method `openid_request' using custom access grant class.

### ISSUE THREAD

**Issue by phlegx** [doorkeeper-gem/doorkeeper-openid_connect#127]
I use doorkeeper config:

```ruby
# config/initializers/doorkeeper.rb
...
access_token_class 'Oauth::AccessToken'
access_grant_class 'Oauth::AccessGrant'
application_class 'Oauth::Application'
```

Call `POST "/oauth/token"` I get:

```
NoMethodError (undefined method `openid_request' for #<Oauth::AccessGrant:0x00005593c7743f28>):

activemodel (6.0.3.2) lib/active_model/attribute_methods.rb:432:in `method_missing'
doorkeeper-openid_connect (325068fd2f38) lib/doorkeeper/openid_connect/oauth/authorization_code_request.rb:13:in `after_successful_response'
doorkeeper (5.4.0) lib/doorkeeper/oauth/base_request.rb:16:in `authorize'
```

If I remove `access_grant_class 'Oauth::AccessGrant'` config. All works fine.

Here my `Oauth::AccessGrant` class:

```ruby
module Oauth
  class AccessGrant < ApplicationRecord
    include ::Doorkeeper::Orm::ActiveRecord::Mixins::AccessGrant
  end
end
```

Maybe in this line:
https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/7e8e58c0a44c6334fb0883437f4cdf6c7cce79b5/lib/doorkeeper/openid_connect/orm/active_record/access_grant.rb#L17

the `access_grant_class` config must be used if set in config.

### Workaround

```ruby
module Oauth
  class AccessGrant < ApplicationRecord
    include ::Doorkeeper::Orm::ActiveRecord::Mixins::AccessGrant

    # Bugfix: see https://github.com/doorkeeper-gem/doorkeeper-openid_connect/issues/127
    has_one :openid_request,
            class_name: 'Doorkeeper::OpenidConnect::Request',
            inverse_of: :access_grant,
            dependent:  :delete
  end
end
```

**Comment by toupeira** [comment]
@phlegx thanks for the report! I'm not sure if we already have access to Doorkeeper's configuration when that `prepend` call happens. :thinking: 

But the `has_one` association is defined at https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/68459f942f5431b2fcae1df3254402a4b2efb3c1/lib/doorkeeper/openid_connect/orm/active_record/access_grant.rb#L8-L11, so I think you should be able to replace your copy with `prepend ::Doorkeeper::OpenidConnect::AccessGrant`?

Let me know if that works and is an acceptable solution, and I'll add a note to the README similar to https://doorkeeper.gitbook.io/guides/configuration/models. We could also support `include` in addition to `prepend` to make it look more consistent.

**Comment by phlegx** [comment]
So, I should put `prepend ::Doorkeeper::OpenidConnect::AccessGrant` in my `AccessGrant` model instead of the `has_one` relation workaround?

**Comment by toupeira** [comment]
@phlegx yes, that should pull in the `has_one` definition and any other future changes (`prepend` acts similarly to `include`). Let me know if that works for you!

I was also curious now if we could just monkey-patch `Doorkeeper::Orm::ActiveRecord::Mixins::AccessGrant` rather than `Doorkeeper::Orm::ActiveRecord::AccessGrant`, but I couldn't find a way to inject code into the existing `included` block there (getting a `ActiveSupport::Concern::MultipleIncludedBlocks` error).

**Comment by jcdennen** [comment]
Just adding a note here that I needed to specify:
```ruby
    has_one :openid_request,
            class_name: 'Doorkeeper::OpenidConnect::Request',
            inverse_of: :access_grant,
            dependent:  :delete
```

_and_ include `foreign_key: 'access_grant_id'` due to my team customizing the `AccessGrant` `table_name`. Without the `foreign_key` constraint specified, I received the following MySQL error:
```sql
Mysql2::Error: Unknown column 'oauth_openid_requests.{custom_table_name}_id' in 'where clause': SELECT  `oauth_openid_requests`.* FROM `oauth_openid_requests` WHERE `oauth_openid_requests`.`{custom_table_name}_id` = X LIMIT 1
```

The schema at this point had already been using `access_grant_id` as the column name
