### ISSUE TITLE
`kid` value in headers in different format after upgrading from 1.8.3 to 1.8.5

### ISSUE THREAD

**Issue by jessieay** [doorkeeper-gem/doorkeeper-openid_connect#193]
This may not be an issue for everyone but I wanted to post an issue warning to others who are upgrading or might be facing an issue with the upgrade as this upgrade (`1.8.3` -> `1.8.5`) caused an authentication incident for my team today.

##  Source of the problem

The root of the issue is this pull request: https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/177

This was [called out as a potential issue](https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/177#issuecomment-1338902262) in the PR itself by @nbulaj .

Specifically, [this line of code](https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/01903c81a2b6237a3bf576ed45864f69ef20184e/lib/doorkeeper/openid_connect/id_token.rb#L37).

The OpenID kid is an opaque value that is supposed to identify public keys. `json-jwt` and `ruby-jwt` implement the kid slightly differently:

[`kid` format for json-jwt](https://github.com/nov/json-jwt/blob/413848c8c93a99093cbb68f198004848f62ecdbd/lib/json/jwk.rb#L28-L38) (used by `1.8.3`)

[`kid` format for ruby-jwt ](https://github.com/jwt/ruby-jwt/blob/18abb5c6e9e6a84cb7793be9a955f9ff1c4505ee/lib/jwt/jwk/hmac.rb#L57-L61)(used by `1.8.5`)

Normally `doorkeeper-openid_connect` manages both the [generation of an OpenID token](https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/9de10c00fcd0b40f0f0a381b860501e566ee87e2/lib/doorkeeper/openid_connect/id_token.rb#L37) and the [endpoint that allows clients to discover the public keys](https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/65526591251549456641f969cb8298a43c66cbd0/app/controllers/doorkeeper/openid_connect/discovery_controller.rb#L104-L115).

In our application, however, we override `Doorkeeper::OpenidConnect::DiscoveryController`  and for the JWK output in our controller we use call `to_jwk`, which uses `json-jwt` NOT `ruby-jwt`

Because our override of `Doorkeeper::OpenidConnect::DiscoveryController`  assumes that the `kid` format will be the format used by `json-jwt`, an upgrade to  doorkeeper-openid_connect`1.8.5` resulted in an incident for us because any service that [validates the signature of a JWT using the `kid` header value](https://self-issued.info/docs/draft-jones-json-web-token-01.html#ReservedHeaderParameterName) against the `kid` in our keys discovery endpoint will raise an error (because the `kid` s do not match).

## What I actually see 

Screenshot of a (test) decoded JWT generated with `1.8.5`:
<img width="867" alt="1 8 5" src="https://user-images.githubusercontent.com/601515/229976741-a8997a80-a4a9-4119-8b3b-e292739b6d40.png">

## What I expect to see

The `kid` should match the `kid` value of my JWK#kid in my discovery keys endpoint (`"OcGcrSBrUtT8mNNNkm1eofXGmOgM4SQtqFgFT8BCszU"`)
Screenshot of a (test) decoded JWT generated with `1.8.3`:
<img width="873" alt="1 8 3" src="https://user-images.githubusercontent.com/601515/229976766-54e52612-8822-41d6-b465-5a834e102bd9.png">

**Comment by stanhu** [comment]
The issue here is that with the switch to https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/177, the `jwt` gem defaults to a key generator of `JWT::JWK::KidAsKeyDigest` instead of `JWT::JWK::Thumbprint`, which implements RFC 7638: https://www.rfc-editor.org/rfc/rfc7638.

It's not obvious that applications need to set to make the `kid` values backwards compatible with `json-jwt`:

```ruby
JWT.configuration.jwk.kid_generator_type = :rfc7638_thumbprint
```

This broke our application because we overrode `Doorkeeper::OpenidConnect::DiscoveryController` to export the `kid` in the RFC 7638 format via `json-jwt`, but `Doorkeeper::OpenidConnect::IdToken` uses a `kid` in the ``JWT::JWK::KidAsKeyDigest` format. Clients would fail because the `kid` listed in the JWKS URL did not match the one provided in the token.

There is a [`json-jwt` discussion to make RFC 7638 the default](https://github.com/jwt/ruby-jwt/pull/481#issuecomment-1144462530) in a future version.

I think v1.8.x of this gem should default to the RFC7638 behavior:

```diff
diff --git a/lib/doorkeeper/openid_connect.rb b/lib/doorkeeper/openid_connect.rb
index b2bca97..d20642e 100644
--- a/lib/doorkeeper/openid_connect.rb
+++ b/lib/doorkeeper/openid_connect.rb
@@ -48,7 +48,7 @@ module Doorkeeper
         else
           OpenSSL::PKey.read(configuration.signing_key)
         end
-      ::JWT::JWK.new(key)
+      ::JWT::JWK.new(key, { kid_generator: JWT::JWK::Thumbprint })
     end
 
     def self.signing_key_normalized
```

I'm not sure if this needs to be customized. What do you think @nbulaj @kristof-mattei?

**Comment by stanhu** [comment]
https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/194 does this.
