### ISSUE TITLE
TODO: Move jws_private_key and jws_public_key to a lamba expression

### ISSUE THREAD

**Issue by cickes** [doorkeeper-gem/doorkeeper-openid_connect#21]
Is this as easy as moving the private keys to an environment variable with lines delimited by \n?  If so, I can attack.  Otherwise if you'd like to point me in the direction regarding how you'd accomplish via a lambda, I'd also be happy to investigate.

**Comment by cickes** [comment]
Updated with new commit.
https://github.com/doorkeeper-gem/doorkeeper-openid_connect/commit/9053c3fdffa17fb5f429cb5d07abcd0d0a4e774f

**Comment by toupeira** [comment]
@cickes sorry I just saw your issue now, I removed that TODO from the README because it's straightforward to use environment variables:

```ruby
jws_private_key ENV['JWS_PRIVATE_KEY']
```

or files:

```ruby
jws_private_key File.read(ENV['JWS_PRIVATE_KEY_PATH'])
```

If you use the `dotenv-rails` gem [newlines should be handled correctly](https://github.com/bkeepers/dotenv#usage).

I'm releasing a new version soon and will add these examples to the README!
