### ISSUE TITLE
Support configurable signing algorithms

### ISSUE THREAD

**Issue by gigr** [doorkeeper-gem/doorkeeper-openid_connect#25]
Hiya! I was going to fork and put up a pull request, but I figured instead I'd make an issue and get feedback on the approach I was planning.

In a nutshell, it would be nice to support algorithms other than the stock `RS256`. In particular, I would like to support signing with the algorithms that the [omniauth-openid-connect](https://github.com/jjbohn/omniauth-openid-connect) gem supports, outlined on [these lines](https://github.com/jjbohn/omniauth-openid-connect/blob/00dd96b/lib/omniauth/strategies/openid_connect.rb#L203-L215).

Personally, I have a vested interest in supporting the MAC-based algorithms, but naturally we'd like to get to a point where all of the [JWA spec](https://tools.ietf.org/html/rfc7518#section-3) is supported. Anyway, my plan was this:

 - Add a new configuration option—`signing_algorithm`—to `Doorkeeper::OpenidConnect::Config`.
 - Add validation to ensure that only the appropriate options are supported.
 - Update `DiscoveryController` to support the different types of algorithms
 - Ensure `Doorkeeper::OpenidConnect::IdToken` supports the different algorithms.

I'm sure I've missed some things, but would a change like this be welcome?

**Comment by toupeira** [comment]
Hi there @gigr! Yes this change would be very welcome and your plan sounds about right, though I haven't yet looked into the exact requirements for the other algorithms. But we use [json-jwt](https://github.com/nov/json-jwt/) which supports most of them, so it really should just be a matter of figuring out how to configure the necessary keys/secrets.

We also need to make sure `DiscoveryController#keys_response` includes the required parameters for the JWKS, see [RFC 7517](https://tools.ietf.org/html/rfc7517).

Actually I just realized we're not using `jws_public_key`, since the public key can be extracted from the private one. So maybe it would be possible to replace the `jws_*` settings with a `signing_key` setting which would be responsible for returning an object that can be passed to `JSON::JWK.new`:

```ruby
Doorkeeper::OpenidConnect.configure do
  signing_key do
    OpenSSL::PKey.read(File.read(ENV['JWS_PRIVATE_KEY'])
  end
end
```

And then maybe we can deduce the `signing_algorithm` value from the class and attributes? If not we could just add it as an explicit setting, as you suggest.

**Comment by gigr** [comment]
Awesome! The idea of adding a `signing_key` makes sense as well. I'll explore that as an option in the PR. I'll be cognizant of the fact that adding a new configuration option for configuring the same thing _could_ break backwards compatibility as well.

I _could_ see this being a few PRs as opposed to one larger one. Do you want me to break it up or would you rather a single, feature-complete PR?

**Comment by toupeira** [comment]
I think we should be fine if we keep `jws_private_key`, log a deprecation warning there, and delegate to the new `signing_key`. I deprecated `jws_public_key` now in 8494eed.

Feel free to submit smaller PRs if you want, but a single one is perfectly fine as well. I don't plan on making a lot of changes in the near future, so you should be safe from merge conflicts ;-)

**Comment by gigr** [comment]
Okay! I'll ping you when I have something to show. Thanks so much!

**Comment by travisofthenorth** [comment]
@gigr is this still on your radar? I would also love to get support for additional algorithms.

**Comment by gigr** [comment]
Not as much. We've found that using the public/private keypair is actually a better solution for our needs.

**Comment by travisofthenorth** [comment]
@toupeira is this PR sufficient? https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/34

**Comment by travisofthenorth** [comment]
@toupeira any idea when you might publish a new version of the gem?

**Comment by toupeira** [comment]
@travisofthenorth very soon, waiting for #36 to get in as well.
