### ISSUE TITLE
Plans to support OIDC Implicit Grant Type

### ISSUE THREAD

**Issue by jsmestad** [doorkeeper-gem/doorkeeper-openid_connect#42]
I'm happy to try and contribute the code if there is any guidance on how best to extend this extension to support the implicit grant type?

**Comment by toupeira** [comment]
I haven't looked into it yet, but according to [this section in the spec](http://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest) I think it would involve supporting `response_type=id_token` (Doorkeeper itself already supports implicit grants).

**Comment by stevenvegt** [comment]
I needed this as well and hacked it into my own branch: https://github.com/stevenvegt/doorkeeper-openid_connect/tree/implicit-flow

It works, but is probably not the _perfect_ approach. We also need a change in doorkeeper itself since the `response_type` param currently does not allow spaces and the implicit flow needs the `id_token token` type.

I would like to get this into master but need some help with integrating this into the lib. Can I apply for support? :)

**Comment by toupeira** [comment]
@stevenvegt cool, thanks for looking into this! It might be a while before I find the time to wrap my head around it though :) Ping me again if you don't hear back over the next few weeks.

Also, I'm curious what your use cases are for the implicit flow, is it JavaScript SPAs or something else?

**Comment by stevenvegt** [comment]
Sounds good!
Yes, I use a Angular4 SPA with https://github.com/IdentityModel/oidc-client-js

**Comment by toupeira** [comment]
This is being implemented in https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/45

**Comment by nashby** [comment]
closing this since it was implemented in #45 (not all the response types are supported but we can add them later)
