### ISSUE TITLE
`prompt=consent` revokes existing access tokens

### ISSUE THREAD

**Issue by nov** [doorkeeper-gem/doorkeeper-openid_connect#64]
It should require explicit consent to issue new code, but shouldn't revoke any other access and/or refresh tokens which are issued at different timing.
https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/master/lib/doorkeeper/openid_connect/helpers/controller.rb#L44

**Comment by toupeira** [comment]
@nov thanks for the report! You're right, this was just the easiest solution I could think of at the time to trigger a reauthorization (and thus explicit consent) in Doorkeeper, but it's definitely not very elegant ;-)

For now I've added a [section about this](https://github.com/doorkeeper-gem/doorkeeper-openid_connect#known-issues) to the README.

I'm not sure how to best approach this since the integration with the Doorkeeper gem is already very leaky. Let me know if you have an idea, otherwise I think I will just remove this code and return a `consent_required` error [as suggested in the OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)

**Comment by nov** [comment]
If you want to support `prompt=consent` in the gem, you’ll need to update doorkeeper gem itself (e.g., defining `reauthorization_required?`) so that you can call the method here to `render :new`
https://github.com/doorkeeper-gem/doorkeeper/blob/master/app/controllers/doorkeeper/authorizations_controller.rb#L27

**Comment by toupeira** [comment]
@nov thanks! Actually I can just call `render :new` directly in this context, this seems to work as expected. See https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/67

**Comment by nov** [comment]
Yeah, it also might be good enough.
I feel it’s a bit trickey though.

**Comment by toupeira** [comment]
@nov yeah I'm also unhappy with the whole approach of hooking into `authenticate_resource_owner!`, there's probably a way to do this more cleanly by using the validations in `Doorkeeper::OAuth::PreAuthorization`.

Anyway, I merged #67 now and released version 1.5.4 of the gem, let me know if you run into any problems!
