### ISSUE TITLE
`nonce` claim does not include in ID Token if doorkeeper's default view

### ISSUE THREAD

**Issue by nhosoya** [doorkeeper-gem/doorkeeper-openid_connect#76]
The view generated by the command `rails generate doorkeeper:views` of the doorkeeper gem does not contain a `nonce`. So even if I add a nonce parameter to Authentication Request, nonce does not include in the issued ID token.

Of course I understand that I can solve the problem by adding hidden_field_tag nonce to view, but I think it is difficult to notice this problem.

refs:
https://github.com/doorkeeper-gem/doorkeeper/blob/adea1d22cd1040b7d62bd35974e4fab0e588910f/app/views/doorkeeper/authorizations/new.html.erb#L22-L43

**Comment by toupeira** [comment]
@nhosoya well this is described in [the README](https://github.com/doorkeeper-gem/doorkeeper-openid_connect#nonces) ;-)

I originally wanted to add this [upstream in the Doorkeeper gem](https://github.com/doorkeeper-gem/doorkeeper/pull/897), but it was rejected because it's specific to OIDC.

It would be great if this was more dynamic along the lines of https://github.com/doorkeeper-gem/doorkeeper/pull/420, but I don't have time ATM to look into this.

**Comment by nhosoya** [comment]
@toupeira 
Thanks! I missed it... 😥

> It would be great if this was more dynamic along the lines of [doorkeeper-gem/doorkeeper#420](https://github.com/doorkeeper-gem/doorkeeper/pull/420), but I don't have time ATM to look into this.

I agree with you, but I can not propose a good implementation right now.
Should I close this issue?
